### ISSUE TITLE
Hiera

### ISSUE THREAD

**Issue by Oyabi** [thias/puppet-samba#12]
Hi, 
it is possible to use your module with hiera ? Can you write some example in the doc please?
And can you add a function for create folder automatically?
Thank you.

Regards.

**Comment by thias** [comment]
YAML example added in b3dca590d0e5a2b539c0a5a11f8f0356e1b04ecd.

Regarding automatically creating directories, it can't be done in a nice and clean way, since each share could then have multiple attributes which would then be relevant only to its `file` resource and need to be filtered out from the samba configuration. And if your intention was to be able to add parts of the configuration from other places in the puppet catalog, that would require switching to use concat for the configuration file. Both of these changes are invasive and add complexity for little gain (IMHO), so I'll avoid them for now.

A perfectly clean PR could change my mind, though :-)
