### ISSUE TITLE
samba4

### ISSUE THREAD

**Issue by sethlyons** [thias/puppet-samba#16]
do you have any plans to extend this module to support samba4?  i'm happy to help if you do.

**Comment by thias** [comment]
Short answer : No.

Long answer : It's because Samba 4 is quite a different beast... I had started creating a `samba4` module a while back, but then I discovered that the version shipped in Red Hat Enterprise Linux has all of the Kerberos part disabled since that would make it ship a duplicate stack (RHEL already includes MIT Kerberos, Samba 4 includes Heimdall Kerberos), and the whole Active Directory replacement was what I was looking for...

**Comment by sethlyons** [comment]
if i add support for samba4 for freebsd to this module, would you be open to merging it?  if not i can fork this and maintain my own version.

**Comment by thias** [comment]
If it's clean and doesn't create problems with the existing samba 3 support, then I'd be open to reviewing and merging changes, yes. But given how different samba 4 is, I suggest you review what needs to be done first, then decide if it's more worth updating this module or creating a new one :-)
